### ISSUE TITLE
Exception while stopping a process using prcoess name

### ISSUE THREAD

**Issue by koustubh25** [supervisorphp/supervisor#15]
I am trying to list own the Supervisor processes and then trying to stop some of them. Below is my code.

```
<?php

require_once __DIR__.'/vendor/autoload.php';
use Supervisor\Supervisor;
use Supervisor\Connector\XmlRpc;
use fXmlRpc\Client;
use fXmlRpc\Transport\HttpAdapterTransport;
use Ivory\HttpAdapter\Guzzle5HttpAdapter;

use Supervisor\Configuration\Configuration;
use Supervisor\Configuration\Section\Supervisord;
use Supervisor\Configuration\Section\Program;
use Indigo\Ini\Renderer;

use Supervisor\Exception\Fault;
use Supervisor\Exception\Fault\BadName;


class supervisor_apis{

    private function get_supervisor($ip, $port, $username = null, $password = null) {

        $guzzleClient = new \GuzzleHttp\Client ( [
            'auth' => [
                $username,
                $password
            ]
        ] );


        $client = new Client ( 'http://' . $ip .':' . $port . '/RPC2', new HttpAdapterTransport ( new Guzzle5HttpAdapter ( $guzzleClient ) ) );

        $connector = new XmlRpc ( $client );

        $supervisor = new Supervisor ( $connector );

        return $supervisor;
    }

    public function get_all_processes($ip = "127.0.0.1", $port = "9001"){
        $supervisor = self::get_supervisor($ip, $port);
        $processes = $supervisor->getAllProcesses();
        foreach($processes as &$process) {
            $payload = $process->getPayload();
            //echo $process . "\r\n";
            return $process;
        }

    }

    public function stop_process($ip = "127.0.0.1", $port = "9001", $name){
        $supervisor = self::get_supervisor($ip, $port);
        echo "*******\r\n" . "Now printing stop process result for " . $name . " \r\n";
        try{
            $supervisor->stopProcess($name);
        } catch (BadName $e) {
        // handle bad name error here
            echo $e;
        } catch (Fault $e) {
        // handle any other errors here
        }
    }
}

$sup = new supervisor_apis();
$process = $sup->get_all_processes();
echo $process . "\r\n";
$sup->stop_process("127.0.0.1", "9001", (string)$process);

?>
```
Here is the output
```
Now printing stop process result for pdf_convert_00 
exception 'Supervisor\Exception\Fault\BadName' with message 'BAD_NAME: pdf_convert_00' in /projects/mv2/millvi-system-monitoring/supervisor/lib/vendor/supervisorphp/supervisor/src/Exception/Fault.php:86
Stack trace
#0 /projects/mv2/test-system-monitoring/supervisor/lib/vendor/supervisorphp/supervisor/src/Connector/XmlRpc.php(47): Supervisor\Exception\Fault::create('BAD_NAME: pdf_c...', 10)
#1 /projects/mv2/test-system-monitoring/supervisor/lib/vendor/supervisorphp/supervisor/src/Supervisor.php(110): Supervisor\Connector\XmlRpc->call('supervisor', 'stopProcess', Array)
#2 /projects/mv2/test-system-monitoring/supervisor/lib/supervisor_apis.php(75): Supervisor\Supervisor->__call('stopProcess', Array)
#3 /projects/mv2/test-system-monitoring/supervisor/lib/supervisor_apis.php(75): Supervisor\Supervisor->stopProcess('pdf_convert_00')
#4 /projects/mv2/test-system-monitoring/supervisor/lib/supervisor_apis.php(94): supervisor_apis->stop_process('127.0.0.1', '9001', 'pdf_convert_00')

```
I am not sure if it is a genuine issue or I am doing something wrong here.

**Comment by j-schumann** [comment]
Check if the process you want to stop is in a process group (inspect $process->getPayload(), see the array structure http://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.stopProcess).

If yes you probably have to give "groupname:processname" to stopProcess, see http://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.stopProcess

**Comment by sagikazarmark** [comment]
Thanks for the help @j-schumann.

I agree, this might be the problem and the first to check.

@koustubh25 can you maybe paste your supervisor config here if the advice above does not help?

**Comment by koustubh25** [comment]
Yes, adding "groupname:processname" does work. 
Thanks a lot.  @j-schumann  @sagikazarmark
