### ISSUE TITLE
Configuring RPC interface

### ISSUE THREAD

**Issue by gyaaniguy** [supervisorphp/supervisor#26]
Getting a error , where the RPC server cannot be found
```
PHP Fatal error:  Uncaught RuntimeException: Error creating resource: [message] fopen(http://127.0.0.1:9001/RPC2): failed to open stream: Connection refused
[file] /mnt/e/work/code/web/twitter/src/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324 in /mnt/e/work/code/web/twitter/src/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:253
Stack trace:
#0 /mnt/e/work/code/web/twitter/src/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(335): GuzzleHttp\Handler\StreamHandler->createResource()
#1 /mnt/e/work/code/web/twitter/src/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(52): GuzzleHttp\Handler\StreamHandler->createStream()
#2 /mnt/e/work/code/web/twitter/src/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\StreamHandler->__invoke()
#3 /mnt/e/work/code/web/twitter/src/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#4 /mnt/e/work/code/web/twitter/src/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Mid in /mnt/e/work/code/web/twitter/src/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/TransportException.php on line 35
```
Does supervisord need to be configured to be able to use this library ? This page suggests so: http://supervisord.org/xmlrpc.html#rpcinterface-factories . But I can't find anything on how to configure this library.

What else could be the issue ?

**Comment by KevinVonJocoon** [comment]
What does your supervisord.conf look like? (e.g. /etc/supervisor/supervisord.conf)
Do you even have it installed on your machine?

We're running our supervisor instances at our company in Docker containers which run quite plainly like this (lots of comments included...):

```
[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[inet_http_server]
port = *:9001

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor            ; ('AUTO' child log dir, default $TEMP)
nodaemon=true

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

; The [include] section can just contain the "files" setting.  This
; setting can list multiple files (separated by whitespace or
; newlines).  It can also contain wildcards.  The filenames are
; interpreted as relative to this file.  Included files *cannot*
; include files themselves.

[include]
files = /etc/supervisor/conf.d/*.conf
```

The author of this package provides us a docker-compose.yml with an example supervisor container (from Dockerhub supervisorphp/supervisor:latest). Didn't test it with this image, we're installing our supervisord via ```apt-get install -y supervisor``` in the Dockerfile.

Are you running supervisord locally or in a Docker container? Any firewalls blocking access?

By the way, it looks a little bit like you're using WSL (/mnt/e/ looks pretty much like these Windows-HDD-Linux-Mountpoints). I'm not sure what you're trying to achieve.

**Comment by gyaaniguy** [comment]
Solved - 
conf file was missing this: 
[inet_http_server]
port = 127.0.0.1:9001
